# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c66c651da543ca5efc4a45c0c1ba1658f9186cc745790cafc832b4bf8ffafb9fa1778fc98996902eb77bc914b65e2d60e18e3a354f45122397bd5f4333055abf

test:
  secret_key_base: 155838b36af83d0a36790a87c4770ed919f5143f3cc65c2ad6b659ace73efdfa5e1e8237019792d678b2906da3b3afaa3fa96480a4ade8eec55dc2707e26ba7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
